- hosts: localhost
  tasks:
  - name : create a cron job
    cron:
        name: "Copy all rsnapshot backups from <hostname>"
        minute: "0"
        hour: "1"
        job: "mkdir /tmp/jaladi"
        user: root
        cron_file: rsync_cron
        state: present
